import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";

export async function POST(request: NextRequest) {
  const supabase = await createClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) return NextResponse.json({ error: "Authentication required" }, { status: 401 }); const { data: profile } = await supabase.from("profiles").select("role").eq("id", user.id).single(); if (profile?.role !== "instructor") return NextResponse.json({ error: "Instructor access required" }, { status: 403 });
  const body = await request.json(); const courseId = String(body.courseId ?? ""); const emails = [...new Set((Array.isArray(body.emails) ? body.emails : String(body.emails ?? "").split(/[\s,;]+/)).map((email: string) => email.trim().toLowerCase()).filter(Boolean))]; if (!courseId || !emails.length) return NextResponse.json({ error: "courseId and at least one email are required" }, { status: 400 });
  const { data: course } = await supabase.from("courses").select("status").eq("id", courseId).single(); if (!course || course.status !== "published") return NextResponse.json({ error: "Only published courses can be bulk-enrolled" }, { status: 409 }); const { data: learners } = await supabase.from("profiles").select("id,email").eq("role", "learner").in("email", emails); const byEmail = new Map((learners ?? []).map((learner) => [learner.email.toLowerCase(), learner])); const { data: existing } = await supabase.from("enrollments").select("learner_id").eq("course_id", courseId).in("learner_id", (learners ?? []).map((learner) => learner.id)); const existingIds = new Set((existing ?? []).map((row) => row.learner_id));
  const results = []; for (const email of emails) { const learner = byEmail.get(email); if (!learner) { results.push({ email, status: "unknown" }); continue; } if (existingIds.has(learner.id)) { results.push({ email, status: "already_enrolled" }); continue; } const { error } = await supabase.from("enrollments").insert({ course_id: courseId, learner_id: learner.id }); results.push({ email, status: error?.code === "23505" ? "already_enrolled" : error ? "error" : "newly_enrolled" }); }
  return NextResponse.json({ courseId, results });
}
