"use client";

import { useState } from "react";
import Link from "next/link";
import { ArrowLeft, CheckCircle2, Circle, MessageSquare, Send } from "lucide-react";

type Props = { course: { id: string; title: string; description: string; category: string; status: string; instructor?: string; lessons: { id: string; title: string; content: string; position: number }[] }; enrollment: { id: string; progress: string } | null; completedLessonIds: string[] };
export default function CourseDetailClient({ course, enrollment: initialEnrollment, completedLessonIds }: Props) {
  const [enrollment, setEnrollment] = useState(initialEnrollment); const [completed, setCompleted] = useState<string[]>(completedLessonIds); const [message, setMessage] = useState(""); const [notice, setNotice] = useState("");
  async function enroll() { const response = await fetch("/api/enrollments", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ courseId: course.id }) }); const result = await response.json(); if (!response.ok) return setNotice(result.error ?? "Could not enroll"); setEnrollment({ id: result.id, progress: "not_started" }); setNotice("You’re enrolled. Start with the first lesson."); }
  async function complete(lessonId: string) { const response = await fetch("/api/progress/complete", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ lessonId }) }); const result = await response.json(); if (!response.ok) return setNotice(result.error ?? "Could not update progress"); setCompleted((items) => [...items, lessonId]); setEnrollment((current) => current ? { ...current, progress: result.progress } : current); setNotice(result.progress === "completed" ? "Course completed — congratulations!" : "Lesson marked complete."); }
  async function comment() { const response = await fetch(`/api/courses/${course.id}/comments`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ message }) }); const result = await response.json(); if (!response.ok) return setNotice(result.error ?? "Could not add comment"); setMessage(""); setNotice("Comment added to the activity history."); }
  return <main className="detail-shell"><header className="detail-topbar"><Link href="/" className="back-link"><ArrowLeft size={16} /> Back to workspace</Link><span className="detail-logo">kinship<span>.</span></span></header><div className="detail-wrap"><div className="detail-hero"><div><span className="detail-category">{course.category}</span><h1>{course.title}</h1><p>{course.description}</p><small>By {course.instructor ?? "Kinship instructor"} · {course.lessons.length} lessons</small></div><div className="detail-status">{enrollment ? <><strong>{enrollment.progress.replace("_", " ")}</strong><span>Your progress</span></> : <button className="button button-primary" onClick={enroll}>Enroll in course</button>}</div></div><div className="detail-grid"><section className="lesson-panel"><div className="panel-header"><div><p className="eyebrow">Course path</p><h2>Lessons</h2></div><span className="lesson-count">{completed.length}/{course.lessons.length} complete</span></div><div className="lesson-list">{course.lessons.map((lesson) => <article className="lesson-card" key={lesson.id}><div className="lesson-number">{completed.includes(lesson.id) ? <CheckCircle2 size={19} /> : <Circle size={19} />}</div><div className="lesson-copy"><span>Lesson {lesson.position}</span><h3>{lesson.title}</h3><p>{lesson.content}</p></div>{enrollment && !completed.includes(lesson.id) && <button className="button button-secondary lesson-action" onClick={() => complete(lesson.id)}>Complete</button>}</article>)}</div></section><aside className="comment-panel"><div className="panel-header"><div><p className="eyebrow">Keep the conversation going</p><h2><MessageSquare size={17} /> Notes</h2></div></div><p className="panel-caption">Share a reflection or question with the instructor.</p><textarea value={message} onChange={(event) => setMessage(event.target.value)} placeholder="What stood out to you?" rows={5} /><button className="button button-primary" onClick={comment}><Send size={15} /> Add comment</button></aside></div>{notice && <div className="detail-notice"><CheckCircle2 size={16} />{notice}</div>}</div></main>;
}
